version: '3.9'

networks:
  njcdd-net:
    external: true

services:
  njcdd-web:
    image: anthonysw/njcdd-web:latest
    container_name: njcdd-web
    ports:
      - "${NJCDD_WEB_PORT}:${NJCDD_WEB_PORT}"
    restart: always
    networks:
      - njcdd-net
    healthcheck:
      test: curl "http://njcdd-web:${NJCDD_WEB_PORT}/" >/dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 32m
